
services:
  # Override PostgreSQL for development
  postgres:
    ports:
      - "5432:5432"
    environment:
      # Use the same password as your self-hosted-ai-starter-kit for consistency
      POSTGRES_PASSWORD: Sup3rBIMgod!

  # Enable n8n by default in development
  n8n:
    profiles: []  # Remove profile to always start

  # Ollama for local AI capabilities
  ollama:
    profiles: []  # Enable by default
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Enable monitoring in development
  prometheus:
    profiles: []  # Enable by default

  grafana:
    profiles: []  # Enable by default
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Sup3rBIMgod! # Match other passwords

  # Override frontend port to avoid conflicts
  frontend:
    ports:
      - "3002:3000"  # Map to port 3002 on host (3000 is Grafana, 3001 is docker Grafana)

# Development-specific volumes
volumes:
  # Add any development-specific volume configurations here
  dev-cache:
